export let body = [

    "anal_01_01",
    "anal_01_02",
    "anal_01_03",
    "anal_01_04",
    "anal_01_05",
    "anal_01_06",
    "anal_01_07",
    "anal_01_08",
    "anal_01_09",
    "anal_02_01",
    "anal_02_02",
    "anal_02_03",
    "anal_02_04",
    "anal_02_05",
    "anal_02_06",
    "anal_02_07",
    "anal_02_08",
    "anal_02_09",
   
    "browjob_01_01",
    "browjob_01_02",
    "browjob_01_03",
    "browjob_01_04",
    "browjob_01_05",
    "browjob_02_01",
    "browjob_02_02",
    "browjob_02_03",
    "browjob_02_04",
    "change_cloth_background",
   
    "fella_01_01",
    "fella_01_02",
    "fella_01_03",
    "fella_01_04",
    "fella_01_05",
    "fella_01_06",
    "fella_02_01",
    "fella_02_02",
    "fella_02_03",
    "fella_02_04",
    "fella_02_05",
    "fella_02_06",
    "fg_01",
    "fg_02",
    "fg_03",
    "fg_04",
    "fg_05",
    "fg_06",
    "fuck_01_01",
    "fuck_01_02",
    "fuck_01_03",
    "fuck_01_04",
    "fuck_01_05",
    "fuck_01_06",
    "fuck_02_01",
    "fuck_02_02",
    "fuck_02_03",
    "fuck_02_04",
    "fuck_02_05",
    "fuck_02_06",
  
    "japan_01",
    "japan_02",
    "japan_03",
    "japan_04",
    "japan_05",
    "japan_06",
    "no-image",
    "nude",
    
    "title_select0",
    "title_select1",
    "title_select2",
   
   
    "vampire_01",
    "vampire_02",
    "vampire_03",
    "vampire_04",
    "vampire_05",
    "vampire_06",
    "vampire_07",
    "vampire_08",
    "vampire_09"
  ]
  export let acce = ["acce_body_ribbon_black",
    "acce_body_ribbon_blue",
    "acce_body_ribbon_red",
    "acce_bugen",
    "acce_bunny_black",
    "acce_bunny_red",
    "acce_catu",
    "acce_cat_black",
    "acce_cat_white",
    "acce_cho",
    "acce_choker",
    "acce_collar",
    "acce_fox",
    "acce_glass_black",
    "acce_glass_hard",
    "acce_glass_red",
    "acce_headdress",
    "acce_head_ribbon_black",
    "acce_head_ribbon_red",
    "acce_head_ribbon_white",
    "acce_hibiscus",
    "acce_huwahuwa_black",
    "acce_huwahuwa_white",
    "acce_maho",
    "acce_maru",
    "acce_metal",
    "acce_mono",
    "acce_neck",
    "acce_neck_no",
    "acce_nurse",
    "acce_rose",
    "acce_santa",
    "acce_straw",
    "acce_white"
]
export let bottom = ["bottoms_check_blue",
    "bottoms_check_brown",
    "bottoms_check_gray",
    "bottoms_check_red",
    "bottoms_chino",
    "bottoms_culottes",
    "bottoms_flare_black",
    "bottoms_flare_red",
    "bottoms_flare_white",
    "bottoms_hot_black",
    "bottoms_hot_blue",
    "bottoms_hot_white",
    "bottoms_jeans",
    "bottoms_jersey",
    "bottoms_leggings",
    "bottoms_legs_black",
    "bottoms_legs_white",
    "bottoms_maternity",
    "bottoms_sera_black",
    "bottoms_sera_white",
    "bottoms_sports",
    "bottoms_tiered_black",
    "bottoms_tiered_white",
    "bottoms_tight_black",
    "bottoms_tight_white"
]
 let face=[ "face_batsu1_back",
"face_batsu1_front",
"face_batsu2_back",
"face_batsu2_front",
"face_cold_back_japan",
"face_cold_back_normal",
"face_cold_back_vampire",
"face_cold_front",
"face_cry2_back",
"face_cry2_front",
"face_cry_back",
"face_cry_front",
"face_fsmile2_back_japan",
"face_fsmile2_back_normal",
"face_fsmile2_back_vampire",
"face_fsmile2_front",
"face_fsmile_back_japan",
"face_fsmile_back_normal",
"face_fsmile_back_vampire",
"face_fsmile_front",
"face_hurry_back_japan",
"face_hurry_back_normal",
"face_hurry_back_vampire",
"face_hurry_front",
"face_loneliness_back_japan",
"face_loneliness_back_normal",
"face_loneliness_back_vampire",
"face_loneliness_front",
"face_normal_back_japan",
"face_normal_back_normal",
"face_normal_back_vampire",
"face_normal_front",
"face_shame1_back_japan",
"face_shame1_back_normal",
"face_shame1_back_vampire",
"face_shame1_front",
"face_shame2_back_japan",
"face_shame2_back_normal",
"face_shame2_back_vampire",
"face_shame2_front",
"face_shy_back_japan",
"face_shy_back_normal",
"face_shy_back_vampire",
"face_shy_front",
"face_smile_back",
"face_smile_back_japan",
"face_smile_back_normal",
"face_smile_back_vampire",
"face_smile_front",
"face_surprise_back_japan",
"face_surprise_back_normal",
"face_surprise_back_vampire",
"face_surprise_front",
"face_talk_back_japan",
"face_talk_back_normal",
"face_talk_back_vampire",
"face_talk_front",
"face_temptation_back_japan",
"face_temptation_back_normal",
"face_temptation_back_vampire",
"face_temptation_front",
"face_worry_back_japan",
"face_worry_back_normal",
"face_worry_back_vampire",
"face_worry_front",
"face_wsmile_back",
"face_wsmile_back_japan",
"face_wsmile_back_normal",
"face_wsmile_back_vampire",
"face_wsmile_front"]
export let face_b=face.filter((t)=>{return t.includes("back")})
export let face_f=face.filter((t)=>{return t.includes("front")})

export let outer=["outer_aprondress_back",
"outer_aprondress_front",
"outer_apron_back",
"outer_apron_front",
"outer_apron_salon_back",
"outer_apron_salon_front",
"outer_bre_black",
"outer_bre_blue",
"outer_bre_brown",
"outer_card_black",
"outer_card_brown",
"outer_card_red",
"outer_cloak_poor",
"outer_dahhuru_back",
"outer_dahhuru_front",
"outer_daun_back",
"outer_daun_front",
"outer_eri",
"outer_huwahuwa2_black_back",
"outer_huwahuwa2_black_front",
"outer_huwahuwa2_red_back",
"outer_huwahuwa2_red_front",
"outer_huwahuwa2_white_back",
"outer_huwahuwa2_white_front",
"outer_huwahuwa_black",
"outer_huwahuwa_white",
"outer_jamper",
"outer_mili_back",
"outer_mili_front",
"outer_muffler_check_back",
"outer_muffler_check_front",
"outer_muffler_red_back",
"outer_muffler_red_front",
"outer_muton_back",
"outer_muton_front",
"outer_overall",
"outer_overall2_back",
"outer_overall2_front",
"outer_torenchi_back",
"outer_torenchi_front",
"outer_vampire_back",
"outer_vampire_front",
"outer_white_back",
"outer_white_front"]
export let outer_b=outer.filter((t)=>{return t.includes("back")})
export let outer_f=outer.filter((t)=>{return t.includes("front")})
let hair=[  "hair_normal_back_main_japan",
"hair_normal_back_main_normal",
"hair_normal_back_main_vampire",
"hair_normal_front_main_japan",
"hair_normal_front_main_normal",
"hair_normal_front_main_vampire",
"hair_normal_front_shadow",
"hair_queen_front_main_japan",
"hair_queen_front_main_normal",
"hair_queen_front_main_vampire",
"hair_queen_front_shadow",
"hair_semi_back_main_japan",
"hair_semi_back_main_normal",
"hair_semi_back_main_vampire",
"hair_semi_front_main_japan",
"hair_semi_front_main_normal",
"hair_semi_front_main_vampire",
"hair_semi_front_shadow",
"hair_twin_back_main_japan",
"hair_twin_back_main_normal",
"hair_twin_back_main_vampire",
"hair_twin_front_main_japan",
"hair_twin_front_main_normal",
"hair_twin_front_main_vampire",
"hair_twin_front_shadow"]
export let hair_b=hair.filter((t)=>{return t.includes("back")&&!t.includes("shadow")})
export let hair_s=hair.filter((t)=>{return t.includes("shadow")})
export let hair_f=hair.filter((t)=>{return t.includes("front")&&!t.includes("shadow")})
export let top=[ "tops_bunny",
"tops_bust",
"tops_camisole",
"tops_cut_border",
"tops_cut_color",
"tops_glove_black",
"tops_glove_white",
"tops_happi",
"tops_huriru",
"tops_jersey",
"tops_kizoku",
"tops_maho",
"tops_neck_black",
"tops_neck_no_black",
"tops_neck_no_white",
"tops_neck_white",
"tops_nurse",
"tops_onepiece_black",
"tops_onepiece_white",
"tops_sera_black",
"tops_sera_white",
"tops_sports",
"tops_tanktop_pink",
"tops_tanktop_white",
"tops_tshirt_black",
"tops_tshirt_white",
"tops_tube",
"tops_tunic_poor",
"tops_yshirt_close",
"tops_yshirt_in"]
export let under=[ "under_baby",
"under_bath",
"under_border_black",
"under_border_black2",
"under_border_blue",
"under_border_blue2",
"under_border_green",
"under_border_green2",
"under_border_pink",
"under_border_pink2",
"under_briefs",
"under_bustier",
"under_child",
"under_color",
"under_cute",
"under_diaper",
"under_loincloth",
"under_m",
"under_micro2_black",
"under_micro2_red",
"under_micro2_white",
"under_micro_black",
"under_micro_red",
"under_micro_white",
"under_mizugi_black",
"under_mizugi_blue",
"under_mizugi_white",
"under_net",
"under_pairs",
"under_pink",
"under_plain_black",
"under_plain_black2",
"under_plain_white",
"under_plain_white2",
"under_poor",
"under_ribbon",
"under_rope",
"under_school_blue",
"under_school_new",
"under_school_true",
"under_school_white",
"under_sexy",
"under_shukujo_black",
"under_shukujo_black2",
"under_shukujo_white",
"under_shukujo_white2",
"under_simple",
"under_spats",
"under_star",
"under_sticking",
"under_woolen"]

//心情
//言语
//脚本系统
// class mood {
//   constructor(){
//     this.state=""//happy sad  anger  
//     this.value=0
//   }
//   add(){

//   }
//   get value(){
//    return this.value
//   }
//   set value(value){
//     //if value >50
//      this.value=value
//   }
// }





// class Human {
//   constructor ({mood}){
//     // super(mood)
//     this.mood=mood
//   }
// }
// export default Human